var servers = ['foodnstuff','sigma-cosmetics','max-hardware','phantasy','netlink','rothman-uni','summit-uni','rho-construction','aerocorp','deltaone','joesguns','hong-fang-tea','zer0','silver-helix','the-hub','zb-institute','johnson-ortho','catalyst','millenium-fitness','harakiri-sushi','nectar-net','neo-net','crush-fitness','omega-net','comptek','syscore','iron-gym'];
servers.forEach(hack);

function hack(server_name){
    if(!hasRootAccess(server_name) && !getServerNumPortsRequired(server_name)){
        run("nuke.script", 1, server_name);
    }
    else
        if(getServerSecurityLevel(server_name) != getServerMinSecurityLevel(server_name) && (getHackingLevel() >= getServerRequiredHackingLevel(server_name))){
            while(true){
                run("hack.script", 1, server_name);
            }
        }
}
